spring:
  datasource:
    url: jdbc:mysql://localhost/Grupo-14-BDD-OO2-2020?serverTimezone=UTC
    username: root
    password: ser.23
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
